FROM node:24.12.0-alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

COPY package*.json ./

# IMPORTANT: do NOT set production yet
ENV NODE_ENV=development
ENV WATCHPACK_POLLING true
ENV NEXT_WEBPACK_USEPOLLING true


#these are defined in the github env, not in cloud secrets
ARG API_BASE_URL
ARG NEXT_PUBLIC_LOGIN_URL
ARG NEXT_PUBLIC_USE_DEBUG_LOGS
ARG NEXT_PUBLIC_TASK_URL
ARG NEXT_PUBLIC_USE_EXAMPLE_QUERY

ARG AUTH_PROVIDER
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG OIDC_ISSUER_URL
ARG OIDC_CLIENT_ID
ARG OIDC_CLIENT_SECRET
ARG OIDC_SCOPE

ARG INT_API_BASE_URL
ARG INT_NEXT_PUBLIC_LOGIN_URL
ARG INT_NEXT_PUBLIC_USE_DEBUG_LOGS
ARG INT_NEXT_PUBLIC_TASK_URL
ARG INT_NEXT_PUBLIC_USE_EXAMPLE_QUERY

ARG APPLICATION_MODE

RUN npm install

COPY . /usr/src
# Now switch to production for runtime
ENV NODE_ENV=production \
	API_BASE_URL=$API_BASE_URL \
	NEXT_PUBLIC_LOGIN_URL=$NEXT_PUBLIC_LOGIN_URL \
	NEXT_PUBLIC_USE_DEBUG_LOGS=$NEXT_PUBLIC_USE_DEBUG_LOGS \
	NEXT_PUBLIC_TASK_URL=$NEXT_PUBLIC_TASK_URL \
	NEXT_PUBLIC_USE_EXAMPLE_QUERY=$NEXT_PUBLIC_USE_EXAMPLE_QUERY \
	APPLICATION_MODE=$APPLICATION_MODE \
	AUTH_PROVIDER=$AUTH_PROVIDER \
	NEXTAUTH_SECRET=$NEXTAUTH_SECRET \
	NEXTAUTH_URL=$NEXTAUTH_URL \
	OIDC_ISSUER_URL=$OIDC_ISSUER_URL \
	OIDC_CLIENT_ID=$OIDC_CLIENT_ID \
	OIDC_CLIENT_SECRET=$OIDC_CLIENT_SECRET \
	OIDC_SCOPE=$OIDC_SCOPE

RUN npm run build

EXPOSE 3000
CMD npm run start
